version: '2'
services:
  monitoreo-app:
    image: monitoreo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://monitoreo-mongodb:27017/?waitQueueMultiple=1000
      - SPRING_DATA_MONGODB_DATABASE=monitoreo
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  monitoreo-mongodb:
    extends:
      file: mongodb.yml
      service: monitoreo-mongodb
